
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
    - id: check-json
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
      exclude: ^docs/.*$
    - id: trailing-whitespace
      exclude: README.md
    - id: pretty-format-json
    - id: flake8
#-   repo: https://github.com/PyCQA/bandit
#    sha: master
#    hooks:
#    - id: bandit
#-   repo: https://github.com/PyCQA/pydocstyle
#    sha: master
#    hooks:
#    - id: pydocstyle
-   repo: https://github.com/asottile/pyupgrade
    sha: master
    hooks:
    - id: pyupgrade
-   repo: https://github.com/ambv/black
    sha: master
    hooks:
    - id: black
      language_version: python3.6
      args: [--line-length=79, --skip-string-normalization]
-   repo: https://github.com/pre-commit/mirrors-mypy
    sha: master
    hooks:
    - id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
#-   repo: https://github.com/pre-commit/mirrors-pylint
#    sha: master  # Use the sha / tag you want to point at
#    hooks:
#    -   id: pylint
